<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.12.0" />
    <PackageReference Include="Confluent.Kafka.Extensions.OpenTelemetry" Version="0.4.0" />
    <PackageReference Include="DistributedLock.Redis" Version="1.1.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.76.0" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.76.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.76.0" />
    <PackageReference Include="Grpc.Tools" Version="2.78.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
    <PackageReference Include="Hangfire.Core" Version="1.8.23" />
    <PackageReference Include="IscB2b.Hangfire.RecurringJobAdmin" Version="1.0.4" />
    <PackageReference Include="IscB2b.Hangfire.Redis.StackExchange" Version="1.12.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="10.0.5" />
    <PackageReference Include="Microsoft.Bcl.TimeProvider" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.5" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Zipkin" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.15.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Hangfire" Version="1.15.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Process" Version="1.15.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.15.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.15.0-beta.1" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageReference Include="Serilog.Exceptions.EntityFrameworkCore" Version="8.4.0" />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="4.2.1-nblumhardt-02317" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
    <PackageReference Include="Volo.Abp.AspNetCore.Authentication.JwtBearer" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.BackgroundJobs" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.BackgroundJobs.HangFire" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.BackgroundWorkers.Hangfire" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.BlobStoring" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.Caching.StackExchangeRedis" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.DistributedLocking" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.MongoDB" Version="10.1.1" />
    <PackageReference Include="Volo.Abp.Swashbuckle" Version="10.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LTC.Shared.CrossCuttingConcerns\LTC.Shared.CrossCuttingConcerns.csproj" />
    <ProjectReference Include="..\LTC.Shared.Hosting.AspNetCore\LTC.Shared.Hosting.AspNetCore.csproj" />
  </ItemGroup>

</Project>
