<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>LTC.ProductService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LTC.ProductService.Domain\LTC.ProductService.Domain.csproj" />
    <ProjectReference Include="..\LTC.ProductService.TestBase\LTC.ProductService.TestBase.csproj" />
  </ItemGroup>

</Project>
